repos:
-   repo: local
    hooks:
    -   id: isort
        name: Python import sorting
        description: Runs isort util to sort imports
        entry: isort
        language: python
        types: [python]
    -   id: flake8
        name: Lint Python files
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: ["--config=setup.cfg", "--max-line-length=119"]
        language: python
        types: [python]
    # -   id: hadolint-docker
    #     name: Lint Dockerfiles
    #     description: Runs hadolint Docker image to lint Dockerfiles
    #     language: docker_image
    #     types: ["dockerfile"]
    #     # args: ["--config=setup.cfg"]
    #     entry: ghcr.io/hadolint/hadolint hadolint
    # -   id: hadolint
    #     name: Lint Dockerfiles
    #     description: Runs hadolint to lint Dockerfiles
    #     language: system
    #     args: ["--config=hadolint.yaml"]
    #     types: ["dockerfile"]
    #     entry: hadolint