# repos:
# -   repo: local
#     hooks:
- id: flake8
name: flake8
description: wemake-python-styleguide enforcement
entry: flake8
args: ["--config=setup.cfg"]
language: python
types: [python]
- id: hadolint-docker
name: Lint Dockerfiles
description: Runs hadolint Docker image to lint Dockerfiles
language: docker_image
types: ["dockerfile"]
entry: ghcr.io/hadolint/hadolint hadolint
- id: hadolint
name: Lint Dockerfiles
description: Runs hadolint to lint Dockerfiles
language: system
types: ["dockerfile"]
entry: hadolint